-- Baseline migration - represents the schema as it actually exists today,
-- built by Hibernate's `spring.jpa.hibernate.ddl-auto=update` over time
-- rather than by any tracked migration (see the Database Schema Review's
-- "no versioned migrations" P1 finding). This file has two different jobs
-- depending on which database it runs against:
--
--   1. Existing dev/prod databases (tables already exist): Flyway will
--      NOT execute this file's statements. `spring.flyway.baseline-on-
--      migrate=true` + `spring.flyway.baseline-version=1` tell Flyway to
--      create its history table and mark V1 as already applied without
--      running it, since the schema it describes is already there.
--   2. A brand-new, empty database (fresh clone, CI, new environment):
--      Flyway finds no existing history and no existing tables, so it
--      actually executes this file to build the schema from scratch.
--
-- Column types/constraints/index names below were taken directly from the
-- actual deployed DDL (see RailLens_Database_Schema_Review.md's "Actual
-- Schema (as deployed)" section, extracted via `strings` on the
-- backups/traindb.sql pg_dump) and cross-checked against the current JPA
-- entities (Train.java, Station.java, TrainSchedule.java, User.java,
-- RefreshToken.java) - not guessed or idealized. In particular, this
-- intentionally reproduces the *current, imperfect* state (nullable
-- train_id/station_id/sequence_no, no unique constraint on
-- (train_id, sequence_no), auto-length varchar(255) codes) rather than
-- the improved schema - fixing those is V2's job, kept separate so the
-- baseline migration is a pure, honest snapshot of "what's really there"
-- and the fix is reviewable on its own.

CREATE TABLE stations (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_code VARCHAR(255) NOT NULL,
    station_name VARCHAR(255),
    CONSTRAINT uk_stations_station_code UNIQUE (station_code)
);

CREATE INDEX idx_station_code ON stations (station_code);
CREATE INDEX idx_station_name ON stations (station_name);

CREATE TABLE trains (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    train_name   VARCHAR(255),
    train_number VARCHAR(255) NOT NULL,
    CONSTRAINT uk_trains_train_number UNIQUE (train_number)
);

CREATE INDEX idx_train_number ON trains (train_number);
CREATE INDEX idx_train_name ON trains (train_name);

CREATE TABLE train_schedule (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arrival_time   TIME(0),
    departure_time TIME(0),
    distance       INTEGER,
    sequence_no    INTEGER,
    station_id     BIGINT,
    train_id       BIGINT,
    CONSTRAINT fk_train_schedule_station_id FOREIGN KEY (station_id)
        REFERENCES stations (id) ON DELETE NO ACTION,
    CONSTRAINT fk_train_schedule_train_id FOREIGN KEY (train_id)
        REFERENCES trains (id) ON DELETE NO ACTION
);

CREATE INDEX idx_schedule_station ON train_schedule (station_id);
CREATE INDEX idx_schedule_train ON train_schedule (train_id);

-- users/refresh_tokens were added later (JWT auth feature) via
-- ddl-auto=update, same as the three tables above - included here so the
-- baseline is complete, not because they're older than the rest.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked    BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_refresh_tokens_user_id FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE NO ACTION,
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash)
);

-- Matches RefreshToken.java's explicit @Index(name = "idx_refresh_token_hash", ...)
CREATE UNIQUE INDEX idx_refresh_token_hash ON refresh_tokens (token_hash);
