
CREATE TABLE stations (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_code VARCHAR(255) NOT NULL,
    station_name VARCHAR(255),
    CONSTRAINT uk_stations_station_code UNIQUE (station_code)
);

CREATE INDEX idx_station_code ON stations (station_code);
CREATE INDEX idx_station_name ON stations (station_name);

CREATE TABLE trains (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    train_name   VARCHAR(255),
    train_number VARCHAR(255) NOT NULL,
    CONSTRAINT uk_trains_train_number UNIQUE (train_number)
);

CREATE INDEX idx_train_number ON trains (train_number);
CREATE INDEX idx_train_name ON trains (train_name);

CREATE TABLE train_schedule (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arrival_time   TIME(0),
    departure_time TIME(0),
    distance       INTEGER,
    sequence_no    INTEGER,
    station_id     BIGINT,
    train_id       BIGINT,
    CONSTRAINT fk_train_schedule_station_id FOREIGN KEY (station_id)
        REFERENCES stations (id) ON DELETE NO ACTION,
    CONSTRAINT fk_train_schedule_train_id FOREIGN KEY (train_id)
        REFERENCES trains (id) ON DELETE NO ACTION
);

CREATE INDEX idx_schedule_station ON train_schedule (station_id);
CREATE INDEX idx_schedule_train ON train_schedule (train_id);

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked    BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_refresh_tokens_user_id FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE NO ACTION,
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash)
);

CREATE UNIQUE INDEX idx_refresh_token_hash ON refresh_tokens (token_hash);
